import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MITEHR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Klinfys <a href="https://nextjs.org">openEHR</a> demo
        </h1>

        <p className={styles.description}>
          EHRBase Web Application
        </p>

        <div className={styles.grid}>
          <a href="/ehr" className={styles.card}>
            <h2>EHR &rarr;</h2>
            <p>Show all health records and compositions</p>

          </a>

          <a href="/template" className={styles.card}>
            <h2>Template &rarr;</h2>
            <p>View and upload templates</p>
          </a>

        </div>
      </main>


    </div>
  )
}
