import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JournalSystem1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <img class="ro_logo"
        src="/ro.png"
        alt="ro_logo"
      />



      <main className={styles.main}>
        <h1 className={styles.title}>
          openEHR POC - Strukturerade svarsmallar patologi
        </h1>

        <p className={styles.description}>
          Journalsystem1 web application demo - Region Östergötland
        </p>

        <div className={styles.grid}>
          <a href="/ehr" className={styles.card}>
            <h2>EHR &rarr;</h2>
            <p>Show all health records and compositions</p>

          </a>

          <a href="/template" className={styles.card}>
            <h2>Template &rarr;</h2>
            <p>View and upload templates</p>
          </a>

          <a href="/send_to_inca" className={styles.card}>
            <h2>INCA &rarr;</h2>
            <p>Send data to INCA</p>
          </a>

          <a href="http://localhost:3005/Remiss/" className={styles.card}>
            <h2>Referrals &rarr;</h2>
            <p>Register referral</p>
          </a>


        </div>
      </main>


    </div>
  )
}
